all_assessment_marks_student = [
    {
        "user_id": 4,
        "module_id": 1,
        "assessment_id": 1,
        "lecturer_id": 7,
        "attempt_number": 2,
        "correct_marks": 17,
        "possible_marks": 17,
        "num_of_credits": 12,
        "is_summative": True,
        "module_title": "Version Control and Large Projects",
        "assessment_title": "Git Basics",
        "highest_scoring_attempt": True,
        "passed": True,
        "credits_earned": 12,
    },
    {
        "user_id": 4,
        "module_id": 1,
        "assessment_id": 2,
        "lecturer_id": 7,
        "attempt_number": 1,
        "correct_marks": 5,
        "possible_marks": 10,
        "num_of_credits": 10,
        "is_summative": True,
        "module_title": "Version Control and Large Projects",
        "assessment_title": "Advanced Git",
        "highest_scoring_attempt": True,
        "passed": True,
        "credits_earned": 10,
    },
]
assessment_id_and_data = {
    1: {
        "total_marks_possible": 17,
        "count_of_questions": 3,
        "difficulty_array": [1, 1, 1],
        "tag_array": [6, 6, 6],
        "average_difficulty": 1.0,
        "tag_array_count": Counter({"tag_array": 1}),
    },
    2: {
        "total_marks_possible": 10,
        "count_of_questions": 2,
        "difficulty_array": [3, 2],
        "tag_array": [5, 4],
        "average_difficulty": 2.5,
        "tag_array_count": Counter({"tag_array": 1}),
    },
    10: {
        "total_marks_possible": 0,
        "count_of_questions": 0,
        "difficulty_array": [],
        "tag_array": [],
    },
    11: {
        "total_marks_possible": 0,
        "count_of_questions": 0,
        "difficulty_array": [],
        "tag_array": [],
    },
}
