final_output = [
    {
        "user_id": 4,
        "attempt_number": 1,
        "question_id": 2,
        "question_text": "What does git rebase do?",
        "question_difficulty": 3,
        "answer_given": "moves or combines a sequence of commits to a new base commit",
        "is_correct": True,
        "lecturer_id": 7,
        "num_of_marks": 5,
        "module_id": 1,
        "assessment_id": 2,
        "question_type": 1,
        "is_summative": True,
        "num_of_credits": 10,
        "module_title": "Version Control and Large Projects",
        "assessment_title": "Advanced Git",
        "tag_id": 5,
        "correct_answer": "moves or combines a sequence of commits to a new base commit",
        "feedback": "Well done!",
        "feedforward": "Well done. To learn more about the use cases for rebase see link https://git-scm.com/book/en/v2/Git-Branching-Rebasing",
        "tag_name": ("environments",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": True,
    },
    {
        "user_id": 4,
        "attempt_number": 1,
        "question_id": 3,
        "question_text": "Which symbol is used to select by class using document.querySelector()?",
        "question_difficulty": 2,
        "answer_given": "zzz",
        "is_correct": False,
        "lecturer_id": 9,
        "num_of_marks": 10,
        "module_id": 2,
        "assessment_id": 3,
        "question_type": 2,
        "correct_answer": ".",
        "is_summative": False,
        "num_of_credits": 0,
        "module_title": "Front End Web Development",
        "assessment_title": "DOM Manipulation in JS",
        "tag_id": 1,
        "feedback": "It's the same in CSS",
        "feedforward": "It might be useful to revise CSS selectors first.",
        "tag_name": ("abstract",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": True,
    },
    {
        "user_id": 4,
        "attempt_number": 1,
        "question_id": 4,
        "question_text": "What is the name of an element which denotes a section?",
        "question_difficulty": 1,
        "answer_given": "zzz",
        "is_correct": False,
        "lecturer_id": 9,
        "num_of_marks": 100,
        "module_id": 2,
        "assessment_id": 9,
        "question_type": 2,
        "correct_answer": "section",
        "is_summative": True,
        "num_of_credits": 20,
        "module_title": "Front End Web Development",
        "assessment_title": "Semantic HTML",
        "tag_id": 2,
        "feedback": "It's not a trick question",
        "feedforward": "Make sure you are comfortable with basic HTML first",
        "tag_name": ("boolean",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": True,
    },
    {
        "user_id": 4,
        "attempt_number": 1,
        "question_id": 8,
        "question_text": "1 When is a door not a door",
        "question_difficulty": 3,
        "answer_given": "When it's a jar",
        "is_correct": True,
        "lecturer_id": 9,
        "num_of_marks": 5,
        "module_id": 2,
        "assessment_id": 9,
        "question_type": 2,
        "correct_answer": "When it's a jar",
        "is_summative": True,
        "num_of_credits": 20,
        "module_title": "Front End Web Development",
        "assessment_title": "Semantic HTML",
        "tag_id": 6,
        "feedback": "Truth incarnate",
        "feedforward": "Well done. Look at this book if you want to learn even more.",
        "tag_name": ("git commands",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": True,
    },
    {
        "user_id": 4,
        "attempt_number": 1,
        "question_id": 9,
        "question_text": "2 When is a door not a door",
        "question_difficulty": 3,
        "answer_given": "When it's a jar",
        "is_correct": True,
        "lecturer_id": 9,
        "num_of_marks": 5,
        "module_id": 2,
        "assessment_id": 9,
        "question_type": 2,
        "correct_answer": "When it's a jar",
        "is_summative": True,
        "num_of_credits": 20,
        "module_title": "Front End Web Development",
        "assessment_title": "Semantic HTML",
        "tag_id": 1,
        "feedback": "Truth incarnate",
        "feedforward": "Well done. Look at this book if you want to learn even more.",
        "tag_name": ("abstract",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": True,
    },
    {
        "user_id": 4,
        "attempt_number": 1,
        "question_id": 10,
        "question_text": "3 When is a door not a door",
        "question_difficulty": 3,
        "answer_given": "When it's a jar",
        "is_correct": True,
        "lecturer_id": 9,
        "num_of_marks": 5,
        "module_id": 2,
        "assessment_id": 9,
        "question_type": 2,
        "correct_answer": "When it's a jar",
        "is_summative": True,
        "num_of_credits": 20,
        "module_title": "Front End Web Development",
        "assessment_title": "Semantic HTML",
        "tag_id": 2,
        "feedback": "Truth incarnate",
        "feedforward": "Well done. Look at this book if you want to learn even more.",
        "tag_name": ("boolean",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": True,
    },
    {
        "user_id": 4,
        "attempt_number": 1,
        "question_id": 11,
        "question_text": "4 When is a door not a door",
        "question_difficulty": 3,
        "answer_given": "Huh?",
        "is_correct": False,
        "lecturer_id": 9,
        "num_of_marks": 5,
        "module_id": 2,
        "assessment_id": 9,
        "question_type": 2,
        "correct_answer": "When it's a jar",
        "is_summative": True,
        "num_of_credits": 20,
        "module_title": "Front End Web Development",
        "assessment_title": "Semantic HTML",
        "tag_id": 3,
        "feedback": "YOU SUCK",
        "feedforward": "Make sure to go over the lecture notes for this topic before trying again.",
        "tag_name": ("computational",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": True,
    },
    {
        "user_id": 4,
        "attempt_number": 1,
        "question_id": 12,
        "question_text": "5 When is a door not a door",
        "question_difficulty": 3,
        "answer_given": "Didn't I answer this already?",
        "is_correct": False,
        "lecturer_id": 9,
        "num_of_marks": 5,
        "module_id": 2,
        "assessment_id": 9,
        "question_type": 2,
        "correct_answer": "When it's a jar",
        "is_summative": True,
        "num_of_credits": 20,
        "module_title": "Front End Web Development",
        "assessment_title": "Semantic HTML",
        "tag_id": 4,
        "feedback": "YOU SUCK",
        "feedforward": "Make sure to go over the lecture notes for this topic before trying again.",
        "tag_name": ("decimal",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": True,
    },
    {
        "user_id": 4,
        "attempt_number": 2,
        "question_id": 1,
        "question_text": "What letter do you use after the hyphen to add a commit message?",
        "question_difficulty": 1,
        "answer_given": "m",
        "is_correct": True,
        "lecturer_id": 7,
        "num_of_marks": 5,
        "module_id": 1,
        "assessment_id": 1,
        "question_type": 2,
        "correct_answer": "m",
        "is_summative": True,
        "num_of_credits": 12,
        "module_title": "Version Control and Large Projects",
        "assessment_title": "Git Basics",
        "tag_id": 6,
        "feedback": "Well done! m for message",
        "feedforward": "If this is too easy, it might be time to move onto the Advanced Git assessment",
        "tag_name": ("git commands",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": True,
    },
    {
        "user_id": 4,
        "attempt_number": 2,
        "question_id": 2,
        "question_text": "which command is used to upload your commits to a remote repository?",
        "question_difficulty": 1,
        "answer_given": "adad",
        "is_correct": True,
        "lecturer_id": 7,
        "num_of_marks": 10,
        "module_id": 1,
        "assessment_id": 1,
        "question_type": 2,
        "correct_answer": "push",
        "is_summative": True,
        "num_of_credits": 12,
        "module_title": "Version Control and Large Projects",
        "assessment_title": "Git Basics",
        "tag_id": 6,
        "feedback": "Well done!",
        "feedforward": "Well done. For more information, look at https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes to see how remote repositories work.",
        "tag_name": ("git commands",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": True,
    },
    {
        "user_id": 4,
        "attempt_number": 2,
        "question_id": 8,
        "question_text": "1 When is a door not a door",
        "question_difficulty": 3,
        "answer_given": "ad's a jar",
        "is_correct": False,
        "lecturer_id": 9,
        "num_of_marks": 5,
        "module_id": 2,
        "assessment_id": 9,
        "question_type": 2,
        "correct_answer": "When it's a jar",
        "is_summative": True,
        "num_of_credits": 20,
        "module_title": "Front End Web Development",
        "assessment_title": "Semantic HTML",
        "tag_id": 6,
        "feedback": "YOU SUCK",
        "feedforward": "Make sure to go over the lecture notes for this topic before trying again.",
        "tag_name": ("git commands",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": False,
    },
    {
        "user_id": 4,
        "attempt_number": 2,
        "question_id": 9,
        "question_text": "2 When is a door not a door",
        "question_difficulty": 3,
        "answer_given": "ad it's a jar",
        "is_correct": False,
        "lecturer_id": 9,
        "num_of_marks": 5,
        "module_id": 2,
        "assessment_id": 9,
        "question_type": 2,
        "correct_answer": "When it's a jar",
        "is_summative": True,
        "num_of_credits": 20,
        "module_title": "Front End Web Development",
        "assessment_title": "Semantic HTML",
        "tag_id": 1,
        "feedback": "YOU SUCK",
        "feedforward": "Make sure to go over the lecture notes for this topic before trying again.",
        "tag_name": ("abstract",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": False,
    },
    {
        "user_id": 4,
        "attempt_number": 2,
        "question_id": 10,
        "question_text": "3 When is a door not a door",
        "question_difficulty": 3,
        "answer_given": "ad it's a jar",
        "is_correct": False,
        "lecturer_id": 9,
        "num_of_marks": 5,
        "module_id": 2,
        "assessment_id": 9,
        "question_type": 2,
        "correct_answer": "When it's a jar",
        "is_summative": True,
        "num_of_credits": 20,
        "module_title": "Front End Web Development",
        "assessment_title": "Semantic HTML",
        "tag_id": 2,
        "feedback": "YOU SUCK",
        "feedforward": "Make sure to go over the lecture notes for this topic before trying again.",
        "tag_name": ("boolean",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": False,
    },
    {
        "user_id": 4,
        "attempt_number": 2,
        "question_id": 11,
        "question_text": "4 When is a door not a door",
        "question_difficulty": 3,
        "answer_given": "Huh?",
        "is_correct": False,
        "lecturer_id": 9,
        "num_of_marks": 5,
        "module_id": 2,
        "assessment_id": 9,
        "question_type": 2,
        "correct_answer": "When it's a jar",
        "is_summative": True,
        "num_of_credits": 20,
        "module_title": "Front End Web Development",
        "assessment_title": "Semantic HTML",
        "tag_id": 3,
        "feedback": "YOU SUCK",
        "feedforward": "Make sure to go over the lecture notes for this topic before trying again.",
        "tag_name": ("computational",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": False,
    },
    {
        "user_id": 4,
        "attempt_number": 2,
        "question_id": 12,
        "question_text": "5 When is a door not a door",
        "question_difficulty": 3,
        "answer_given": "When it's a jar",
        "is_correct": False,
        "lecturer_id": 9,
        "num_of_marks": 5,
        "module_id": 2,
        "assessment_id": 9,
        "question_type": 2,
        "correct_answer": "When it's a jar",
        "is_summative": True,
        "num_of_credits": 20,
        "module_title": "Front End Web Development",
        "assessment_title": "Semantic HTML",
        "tag_id": 4,
        "feedback": "YOU SUCK",
        "feedforward": "Make sure to go over the lecture notes for this topic before trying again.",
        "tag_name": ("decimal",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": False,
    },
    {
        "user_id": 4,
        "attempt_number": 3,
        "question_id": 1,
        "question_text": "What letter do you use after the hyphen to add a commit message?",
        "question_difficulty": 1,
        "answer_given": "m",
        "is_correct": True,
        "lecturer_id": 7,
        "num_of_marks": 5,
        "module_id": 1,
        "assessment_id": 1,
        "question_type": 2,
        "correct_answer": "m",
        "is_summative": True,
        "num_of_credits": 12,
        "module_title": "Version Control and Large Projects",
        "assessment_title": "Git Basics",
        "tag_id": 6,
        "feedback": "Well done! m for message",
        "feedforward": "If this is too easy, it might be time to move onto the Advanced Git assessment",
        "tag_name": ("git commands",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": False,
    },
    {
        "user_id": 4,
        "attempt_number": 3,
        "question_id": 2,
        "question_text": "which command is used to upload your commits to a remote repository?",
        "question_difficulty": 1,
        "answer_given": "adad",
        "is_correct": False,
        "lecturer_id": 7,
        "num_of_marks": 10,
        "module_id": 1,
        "assessment_id": 1,
        "question_type": 2,
        "correct_answer": "push",
        "is_summative": True,
        "num_of_credits": 12,
        "module_title": "Version Control and Large Projects",
        "assessment_title": "Git Basics",
        "tag_id": 6,
        "feedback": "What is the opposite of pull?",
        "feedforward": "Make sure to learn the basic git commands before you move on",
        "tag_name": ("git commands",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": False,
    },
]

final_output = [
    {
        "user_id": 4,
        "attempt_number": 1,
        "question_id": 2,
        "question_text": "What does git rebase do?",
        "question_difficulty": 3,
        "answer_given": "moves or combines a sequence of commits to a new base commit",
        "is_correct": True,
        "lecturer_id": 7,
        "num_of_marks": 5,
        "module_id": 1,
        "assessment_id": 2,
        "question_type": 1,
        "is_summative": True,
        "num_of_credits": 10,
        "module_title": "Version Control and Large Projects",
        "assessment_title": "Advanced Git",
        "tag_id": 5,
        "correct_answer": "moves or combines a sequence of commits to a new base commit",
        "feedback": "Well done!",
        "feedforward": "Well done. To learn more about the use cases for rebase see link https://git-scm.com/book/en/v2/Git-Branching-Rebasing",
        "tag_name": ("environments",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": True,
    }
]
