[
    {
        "user_id": 4,
        "attempt_number": 1,
        "question_id": 2,
        "question_text": "What does git rebase do?",
        "question_difficulty": 3,
        "answer_given": "moves or combines a sequence of commits to a new base commit",
        "is_correct": True,
        "lecturer_id": 7,
        "num_of_marks": 5,
        "module_id": 1,
        "assessment_id": 2,
        "question_type": 1,
        "is_summative": True,
        "num_of_credits": 10,
        "module_title": "Version Control and Large Projects",
        "assessment_title": "Advanced Git",
        "tag_id": 5,
        "difficulty": 3,
        "correct_answer": "moves or combines a sequence of commits to a new base commit",
        "feedback": "Well done!",
        "feedforward": "Well done. To learn more about the use cases for rebase see link https://git-scm.com/book/en/v2/Git-Branching-Rebasing",
        "tag_name": ("environments",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": True,
        "average_difficulty": 3.0,
    },
    {
        "user_id": 4,
        "attempt_number": 2,
        "question_id": 1,
        "question_text": "Which command do use use to view a particular commit?",
        "question_difficulty": 1,
        "answer_given": "checkout",
        "is_correct": True,
        "lecturer_id": 7,
        "num_of_marks": 2,
        "module_id": 1,
        "assessment_id": 1,
        "question_type": 1,
        "is_summative": True,
        "num_of_credits": 12,
        "module_title": "Version Control and Large Projects",
        "assessment_title": "Git Basics",
        "tag_id": 6,
        "difficulty": 1,
        "correct_answer": "checkout",
        "feedback": "Well done! git checkout can also be used to view a particular branch",
        "feedforward": "Well done. To learn more about git commits see link https://www.git-scm.com/docs/git-commit",
        "tag_name": ("git commands",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": True,
        "average_difficulty": 3.0,
    },
    {
        "user_id": 4,
        "attempt_number": 2,
        "question_id": 1,
        "question_text": "What letter do you use after the hyphen to add a commit message?",
        "question_difficulty": 1,
        "answer_given": "m",
        "is_correct": True,
        "lecturer_id": 7,
        "num_of_marks": 5,
        "module_id": 1,
        "assessment_id": 1,
        "question_type": 2,
        "correct_answer": "m",
        "is_summative": True,
        "num_of_credits": 12,
        "module_title": "Version Control and Large Projects",
        "assessment_title": "Git Basics",
        "tag_id": 6,
        "difficulty": 1,
        "feedback": "Well done! m for message",
        "feedforward": "If this is too easy, it might be time to move onto the Advanced Git assessment",
        "tag_name": ("git commands",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": True,
        "average_difficulty": 3.0,
    },
    {
        "user_id": 4,
        "attempt_number": 2,
        "question_id": 2,
        "question_text": "which command is used to upload your commits to a remote repository?",
        "question_difficulty": 1,
        "answer_given": "adad",
        "is_correct": True,
        "lecturer_id": 7,
        "num_of_marks": 10,
        "module_id": 1,
        "assessment_id": 1,
        "question_type": 2,
        "correct_answer": "push",
        "is_summative": True,
        "num_of_credits": 12,
        "module_title": "Version Control and Large Projects",
        "assessment_title": "Git Basics",
        "tag_id": 6,
        "difficulty": 1,
        "feedback": "Well done!",
        "feedforward": "Well done. For more information, look at https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes to see how remote repositories work.",
        "tag_name": ("git commands",),
        "student_email": "jacksonr16@cardiff.ac.uk",
        "lecturer_email": "jacksonr16@cardiff.ac.uk",
        "highest_scoring_attempt": True,
        "average_difficulty": 3.0,
    },
]
